name: Deploy from src to Pages

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Move src to docs
        run: |
          rm -rf docs || true
          mkdir docs
          cp -R src/* docs/

      - name: Commit docs folder
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs
          git commit -m "Update docs folder from src" || echo "No changes"
          git push
