name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"] # ou "master", dependendo da sua branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages   # branch usada pelo GitHub Pages
          folder: src        # aqui está o seu index.html