name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Copy src -> docs
        run: |
          rm -rf docs || true
          mkdir docs
          cp -R src/* docs/

      - name: Deploy to gh-pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: main          # branch destino
          folder: gh-pages             # publica a pasta `docs` dentro da gh-pages
          token: ${{ secrets.GITHUB_TOKEN }}
